# Use an official Python runtime as a parent image
FROM python:3-slim
WORKDIR /app
ADD . /app
RUN pip install --trusted-host pypi.python.org Flask
RUN pip install requests
RUN pip install psutil
ENV NAME WeightedRoundRobin
CMD ["python", "w_rr.py"]